### PR TITLE
Add support for SSI in error pages

### PR DESCRIPTION
**Pull request by daniel-ac-martin**
Adds support for Server Side Includes in the error pages. This will allow consumers to create more advanced error pages, including [a GovUK-branded one](https://github.com/UKHomeOffice/docker-nginx-proxy-govuk) for our own purposes.

* Replaces the /50x.html location with a more flexible /nginx-proxy/ location, allowing a variety of error pages to be supported and allowing consumers to add whatever extra static assets they wish.
* Adds an error page for 418 responses
* Adds a very simple 'partials' setup to enable us to very easily add new error pages in the future
* Adds a date and time to all error pages
* Adds support for accessing NAXSI's debug headers

**Note:** This is a breaking change.

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Don't do a release after this. I'd like to make another breaking change. (To support separate error pages for 502's etc.)

**Comment by daniel-ac-martin** [comment]
After our discussion, I've looked into getting the status code out of a variable in the SSI. Seems that is possible. Unfortunately, it doesn't look like I can test for a file's existence in SSI which makes it a bit less useful.

There's a few strategies we could use for handling all the different 50x errors separately. Could we merge this and deal with those in a separate PR? (We could discuss this and I could push to this PR, but there are no regressions in this PR.)

**Comment by daniel-ac-martin** [comment]
@lewismarshall: How about if I change this so that we don't actually use any SSI in here? (Only make it available downstream.)

**Comment by daniel-ac-martin** [comment]
@lewismarshall: Changes made in line with my last comment.

**Comment by lewismarshall** [comment]
LGTM

**Comment by lewismarshall** [comment]
LGTM

**Pull request merged**
