### PR TITLE
Added dynamic listening ports

### PR DESCRIPTION
**Pull request by lewismarshall**
Will need this when use docker `--net=host` as systemd files.

Can be tested as v1.1.3-rc1

### CODE REVIEW

**Comment by lewismarshall** [comment]
Added test for port change and README.md update v1.1.3-rc2.

**Comment by lewismarshall** [comment]
@gambol99 by your command...

**Comment by vaijab** [comment]
LGTM

**Comment by easternbloc** [comment]
:ok_hand:

**Pull request merged**
