### PR TITLE
- removing the http cookie from the default logging options

### PR DESCRIPTION
**Pull request by gambol99**

### CODE REVIEW

**Comment by gambol99** [comment]
@vaijab @lewismarshall @jon-shanks

**Comment by vaijab** [comment]
Goood! LGTM

**Comment by lewismarshall** [comment]
In the name of clean working logs LGTM :+1:

**Comment by vaijab** [comment]
@lewismarshall are you going to merge this or is it going to be @gambol99 ?

**Comment by lewismarshall** [comment]
Pushed as tag v1.1.6 - should be on Quay soon...

**Pull request merged**
