### PR TITLE
Support upstream client certs

### PR DESCRIPTION
**Pull request by daniel-ac-martin**

### CODE REVIEW

**Comment by lewismarshall** [comment]
It'll be really good to add a test for this (maybe using another instance of proxy itself as the server)...

**Comment by daniel-ac-martin** [comment]
Yes, good idea. :-)

If no-one else fancies adding those someone might have to nag me!

**Comment by lewismarshall** [comment]
Would be good if the tests pass but looks good otherwise

**Comment by lewismarshall** [comment]
LGTM

**Pull request merged**
