### PR TITLE
Update nginx version and add basic auth

### PR DESCRIPTION
**Pull request by gileshinchcliff**
Updated openresty version to 1.9.7.4
Added basic auth config
Removed sysdig agent from logs

### CODE REVIEW

**Comment by allandegnan** [comment]
- Does it need to be a file?  Can we not just pass an env?
- Can you fix your editor so it doesn't do that in the future?
- Can we not bump versions so much when making other changes?

I can live with the changes but I'd like @lewismarshall to comment.

**Comment by gileshinchcliff** [comment]
The reason why it's a file, is because it's designed to be used with vault.. So your username and passwords are stored in vault mounted as a file into your container. My understanding is that using a file is meant to be the standard when dealing with secrets not Env vars.

Version bump was to debug an issue I was having which ended up being unrelated. However I can create a separate PR for it if it would help.

**Comment by allandegnan** [comment]
So the pattern is you're going to run a vault sidekick and pull the secret into a shared volume / emptydir?

**Comment by gileshinchcliff** [comment]
yep, from what I can tell that's the agreed pattern. As far as any patterns are agreed right now. But either way we're more likely to be utilising secrets from files than from env vars.

**Comment by lewismarshall** [comment]
Really not sure as to cleanest pattern here, seems like something simpler with just uid and password secret file(s) and no specific extra cfg bit.

Would be really nice to update the PR with just the single clean change and not the readme line endings

**Comment by gileshinchcliff** [comment]
If I was gonna be awkward then I'd argue that removing the trailing whitespace is no bad thing. 

Can you explain what you mean by uuid and password? To use basic auth we would need some sort of htpaswd file, hence we would need some sort of config to create it. 

The way this works we can mount the same file on both the proxy and the container that will be connecting to it form the same source of truth (vault).

I'll add back in the whitespace for you @lewismarshall :)

**Comment by lewismarshall** [comment]
All I meant was remove the need for the config ADD_NGINX_LOCATION_CFG - if you specify a BASIC_AUTH or BASIC_AUTH_1 location - just add this automatically...

We should probably rename to:
`BASIC_AUTH_SECRET` (when secret file specifies users and passwords and we want to generate .htpasswd file)
 and (as a possible extra, maybe later):
`BASIC_AUTH_FILE` (when .htpasswd file is specified directly)

**Comment by gileshinchcliff** [comment]
What would be the value in passing in the .htpasswd file directly? I can't see a case where that would make more sense than passing the username:password file.

Can see why you'd want to add in BASIC_AUTH config as a command, I felt it simplified things to leave it out and use the location config, but to be honest I can go either way.

**Comment by lewismarshall** [comment]
OK so forget the .htpasswd bit but as discussed re move from go.sh to location.sh and remove the need for the ADD_NGINX_LOCATION_CFG variable.

**Comment by lewismarshall** [comment]
LGTM

**Pull request merged**
