### PR TITLE
Add simple drone pipeline

### PR DESCRIPTION
**Pull request by daniel-ac-martin**

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
One of the racy tests seems to be particularly racy in drone. (One of the rate limiting ones.)
How do people feel about disabling it?

**Comment by JoeChapman** [comment]
LGTM

**Comment by daniel-ac-martin** [comment]
Predictably, the ones related to rate limiting are racy.

**Comment by daniel-ac-martin** [comment]
I vote that we disable the racy tests as and when they fail on us in subsequent PRs.
Any objections? Can someone merge this?

**Pull request merged**
