### PR TITLE
Don't run as root

### PR DESCRIPTION
**Pull request by daniel-ac-martin**
Runs as an nginx user instead of root. This is a breaking change and moves the default listen ports to 10080 and 10443.

This is intended to supersede #74.

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
@vaijab: Any thoughts? - The chown'ing here should be more specific.

**Comment by vaijab** [comment]
I am not fully up to speed with nginx-proxy code, but I believe these changes look OK. However, please rebase before merging! :octopus:

**Comment by JoeChapman** [comment]
Why change the default ports?

**Comment by daniel-ac-martin** [comment]
@vaijab: Already done. ;-)
@JoeChapman: The current default ports require root as they are below 1024.

I don't have the ability to merge myself so one of you will need to do it if you are happy.

**Comment by vaijab** [comment]
@daniel-ac-martin 631c392 could be squashed further as that's just a typo fix ;-)

**Comment by daniel-ac-martin** [comment]
@vaijab: Oh I see, I though you just wanted the PR to be up to date with master. We I can look at simplifying the commits. Didn't want to do so straight away as I wanted to credit Joe's work which forms the majority of this PR.

**Comment by JoeChapman** [comment]
LGTM

**Comment by JoeChapman** [comment]
@daniel-ac-martin will you document the default port change, and specifically how to override the default ports?

**Comment by JoeChapman** [comment]
@vaijab you know what this build error means?
`Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)`

**Comment by daniel-ac-martin** [comment]
I'm guessing this is a docker thing.

**Comment by vaijab** [comment]
> you know what this build error means

yeah, the way @lewismarshall configured CI build, means that breakage was inevitable sooner or later. I suggest to switch to `dind` (docker in docker) instead. He knows what I mean. :-)

**Comment by daniel-ac-martin** [comment]
Drone used to work though. Would me removing `--run-priviliged` have broken this?

**Comment by vaijab** [comment]
> Drone used to work though. Would me removing --run-priviliged have broken this?

It used to work, however centos or whatever base image you're using version of docker is now newer or older, hence the error.

**Comment by daniel-ac-martin** [comment]
Right, the CI pipeline is fixed. Can we merge this now?

**Comment by lewismarshall** [comment]
LGTM

**Pull request merged**
